name: scalpelEnv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedops=2.4.41
  - bioconductor-genomicranges=1.54.1
  - bioconductor-gviz=1.46.1
  - bioconductor-rtracklayer=1.62.0
  - gawk=5.1.0
  - r-argparse=2.2.3
  - r-base=4.3.3
  - r-data.table=1.15.4
  - r-dplyr=1.1.4
  - r-ggplot2=3.5.2
  - r-seurat=5.1.0
  - r-stringr=1.5.1
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - salmon=1.10.3
  - samtools=1.20
