name: scalpel_env
channels:
  - bioconda
  - r
  - conda-forge
  - anaconda
dependencies:
  - nextflow
  - salmon
  - r-argparse
  - r-data.table
  - r-dplyr
  - r-tidyr
  - bioconductor-rtracklayer
  - r-stringr
  - bioconductor-mscoreutils
  - samtools
  - bedops
  - bioconductor-genomicranges
  - r-ggplot2
  - r-scales
  - argparse
  - pandas
  - r-httr
  - igraph
  - r-leiden
  - r-reshape
  - r-sctransform
  - r-stringi
